<?php
/**
 * install.php
 * 
 * Interactive Schema Installer & Configuration Bootstraper.
 * Uses a mobile-responsive Bootstrap 5 interface to provision database parameters.
 */

declare(strict_types=1);

error_reporting(E_ALL);
ini_set('display_errors', '1');

$step = isset($_POST['action']) ? $_POST['action'] : 'form';
$error = null;
$success = false;

if ($step === 'setup') {
    $db_host = trim($_POST['db_host'] ?? '');
    $db_name = trim($_POST['db_name'] ?? '');
    $db_user = trim($_POST['db_user'] ?? '');
    $db_pass = $_POST['db_pass'] ?? '';
    $bot_token = trim($_POST['bot_token'] ?? '');
    $channel_id = trim($_POST['channel_id'] ?? '');

    // Basic Input Validation
    if (empty($db_host) || empty($db_name) || empty($db_user) || empty($bot_token)) {
        $error = "All fields except DB Password and Channel ID are strictly required.";
    } else {
        // Attempt PDO DB connection & verify settings
        try {
            $dsn = "mysql:host={$db_host};charset=utf8mb4";
            $options = [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_TIMEOUT => 5 // 5 second timeout for validation
            ];
            $test_pdo = new PDO($dsn, $db_user, $db_pass, $options);
            
            // Create database if it does not exist
            $test_pdo->exec("CREATE DATABASE IF NOT EXISTS `{$db_name}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;");
            $test_pdo->exec("USE `{$db_name}`;");

            // Define tables creation queries
            $tablesSql = [
                "users" => "
                    CREATE TABLE IF NOT EXISTS users (
                        id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                        user_id BIGINT NOT NULL UNIQUE,
                        username VARCHAR(255) NULL,
                        first_name VARCHAR(255) NULL,
                        step TINYINT NOT NULL DEFAULT 1,
                        action_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        is_blocked TINYINT(1) DEFAULT 0,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
                ",
                "callback_logs" => "
                    CREATE TABLE IF NOT EXISTS callback_logs (
                        id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        callback_data VARCHAR(255),
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
                ",
                "worker_logs" => "
                    CREATE TABLE IF NOT EXISTS worker_logs (
                        id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        action_type VARCHAR(100),
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
                "
            ];

            // Execute schema provisioning
            foreach ($tablesSql as $tableName => $sql) {
                $test_pdo->exec($sql);
            }

            // Create optimization and lock indexes on users table
            $indexes = [
                "CREATE UNIQUE INDEX IF NOT EXISTS idx_user_id ON users(user_id);",
                "CREATE INDEX IF NOT EXISTS idx_step ON users(step);",
                "CREATE INDEX IF NOT EXISTS idx_action_timestamp ON users(action_timestamp);",
                "CREATE INDEX IF NOT EXISTS idx_step_timestamp ON users(step, action_timestamp);"
            ];

            foreach ($indexes as $indexSql) {
                try {
                    $test_pdo->exec($indexSql);
                } catch (PDOException $idxEx) {
                    // Index may already exist (compatibility handling under MySQL versions)
                }
            }

            // Generate config.php dynamic values
            $configContent = "<?php" . PHP_EOL;
            $configContent .= "/**" . PHP_EOL;
            $configContent .= " * Dynamic Telegram Bot Configuration File." . PHP_EOL;
            $configContent .= " * Auto-generated by install.php" . PHP_EOL;
            $configContent .= " */" . PHP_EOL . PHP_EOL;
            $configContent .= "declare(strict_types=1);" . PHP_EOL . PHP_EOL;
            $configContent .= "define('DB_HOST', " . var_export($db_host, true) . ");" . PHP_EOL;
            $configContent .= "define('DB_NAME', " . var_export($db_name, true) . ");" . PHP_EOL;
            $configContent .= "define('DB_USER', " . var_export($db_user, true) . ");" . PHP_EOL;
            $configContent .= "define('DB_PASS', " . var_export($db_pass, true) . ");" . PHP_EOL;
            $configContent .= "define('TELEGRAM_BOT_TOKEN', " . var_export($bot_token, true) . ");" . PHP_EOL;
            $configContent .= "define('CHANNEL_ID', " . var_export($channel_id, true) . ");" . PHP_EOL;

            if (file_put_contents(__DIR__ . '/config.php', $configContent) === false) {
                throw new Exception("Unable to write config.php. Please ensure directory write permissions.");
            }

            $success = true;
        } catch (PDOException $e) {
            $error = "Database Error: " . $e->getMessage();
        } catch (Exception $e) {
            $error = "Installation Error: " . $e->getMessage();
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Telegram Funnel Bot Installer</title>
    <!-- Modern Bootstrap Styles -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Inter', sans-serif;
            background-color: #f3f4f6;
            color: #1f2937;
        }
        .card {
            border: none;
            border-radius: 12px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
        }
    </style>
</head>
<body class="py-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 col-lg-6">
                
                <div class="text-center mb-4">
                    <h2 class="fw-bold text-primary">Telegram Funnel Bot</h2>
                    <p class="text-muted">Enterprise-Grade Setup Wizard</p>
                </div>

                <?php if ($success): ?>
                    <div class="card bg-white p-4">
                        <div class="card-body text-center">
                            <div class="mb-3">
                                <span class="badge bg-success py-2 px-3 fs-5">✓ Success</span>
                            </div>
                            <h3 class="fw-bold mb-3">Installation Completed!</h3>
                            <p class="text-secondary align-left text-start">
                                The schema has been successfully created and your parameters have been persisted to <code>config.php</code>.
                            </p>
                            
                            <hr>

                            <h5 class="fw-bold text-start text-dark mb-2">Next Steps:</h5>
                            <ol class="text-start fs-7 text-secondary">
                                <li class="mb-2"><strong>Set Up Telegram Webhook</strong>: Run this HTTP trigger in your browser (replace URL with your domain):<br>
                                    <code class="d-block bg-light p-2 mt-1 border-radius text-break" style="font-size: 11px;">https://api.telegram.org/bot<?php echo htmlspecialchars($bot_token); ?>/setWebhook?url=https://yourdomain.com/webhook_handler.php&allowed_updates=["message","callback_query","chat_member"]</code>
                                </li>
                                <li class="mb-2"><strong>Start Watchdog Cron</strong>: Launch the worker daemon inside your server Terminal:<br>
                                    <code class="d-block bg-light p-2 mt-1 border-radius text-break" style="font-size: 11px;">chmod +x cron_job.sh && ./cron_job.sh</code>
                                </li>
                                <li class="mb-2"><strong>Channel Check</strong>: Ensure your Telegram Bot is added as an <strong>Administrator</strong> inside your Telegram channel.</li>
                            </ol>

                            <div class="mt-4">
                                <a href="install.php" class="btn btn-outline-primary btn-sm">Configure Again</a>
                            </div>
                        </div>
                    </div>
                <?php else: ?>
                    <div class="card bg-white p-4">
                        <div class="card-body">
                            <form method="POST">
                                <input type="hidden" name="action" value="setup">

                                <?php if ($error): ?>
                                    <div class="alert alert-danger" role="alert">
                                        <?php echo htmlspecialchars($error); ?>
                                    </div>
                                <?php endif; ?>

                                <h5 class="fw-bold mb-3 text-secondary border-bottom pb-2">MySQL Database Details</h5>
                                
                                <div class="mb-3">
                                    <label class="form-label font-medium mb-1">Database Host</label>
                                    <input type="text" class="form-control" name="db_host" value="localhost" placeholder="e.g. localhost, 127.0.0.1" required>
                                </div>

                                <div class="mb-3">
                                    <label class="form-label font-medium mb-1">Database Name</label>
                                    <input type="text" class="form-control" name="db_name" placeholder="e.g. telegram_funnel_db" required>
                                </div>

                                <div class="row">
                                    <div class="col-sm-6 mb-3">
                                        <label class="form-label font-medium mb-1">Database User</label>
                                        <input type="text" class="form-control" name="db_user" placeholder="root" required>
                                    </div>
                                    <div class="col-sm-6 mb-3">
                                        <label class="form-label font-medium mb-1">Database Password</label>
                                        <input type="password" class="form-control" name="db_pass" placeholder="Leave empty if none">
                                    </div>
                                </div>

                                <h5 class="fw-bold mt-4 mb-3 text-secondary border-bottom pb-2">Telegram Integration Keys</h5>

                                <div class="mb-3">
                                    <label class="form-label font-medium mb-1">Telegram Bot Token</label>
                                    <input type="text" class="form-control text-monospace" style="font-size: 13px;" name="bot_token" placeholder="123456789:ABCdefGhIJKlmNoPQRsTUVwxyZ" required>
                                    <div class="form-text">Generate via @BotFather in Telegram.</div>
                                </div>

                                <div class="mb-3">
                                    <label class="form-label font-medium mb-1">Channel ID (Optional)</label>
                                    <input type="text" class="form-control" name="channel_id" placeholder="e.g. -100123456789">
                                    <div class="form-text">Telegram channel numeric identifier (with -100 prefix).</div>
                                </div>

                                <div class="mt-4 pt-2">
                                    <button type="submit" class="btn btn-primary w-full w-100 py-2 fw-semibold">Install & Initialize Database</button>
                                </div>
                            </form>
                        </div>
                    </div>
                <?php endif; ?>

            </div>
        </div>
    </div>
</body>
</html>
