/**
 * phpCodeData.ts
 * 
 * Houses safe static replicas of the generated PHP core scripts for display and manual copy.
 */

export const phpFiles: Record<string, { desc: string; val: string; lang: 'php' | 'bash' }> = {
  'install.php': {
    desc: 'Mobile-responsive Bootstrap 5 installer of credentials, automatic schema generator, and setup wizard.',
    lang: 'php',
    val: `<?php
/**
 * install.php
 * 
 * Interactive Schema Installer & Configuration Bootstraper.
 * Uses a mobile-responsive Bootstrap 5 interface to provision database parameters.
 */

declare(strict_types=1);

error_reporting(E_ALL);
ini_set('display_errors', '1');

$step = isset($_POST['action']) ? $_POST['action'] : 'form';
$error = null;
$success = false;

if ($step === 'setup') {
    $db_host = trim($_POST['db_host'] ?? '');
    $db_name = trim($_POST['db_name'] ?? '');
    $db_user = trim($_POST['db_user'] ?? '');
    $db_pass = $_POST['db_pass'] ?? '';
    $bot_token = trim($_POST['bot_token'] ?? '');
    $channel_id = trim($_POST['channel_id'] ?? '');

    // Basic Input Validation
    if (empty($db_host) || empty($db_name) || empty($db_user) || empty($bot_token)) {
        $error = "All fields except DB Password and Channel ID are strictly required.";
    } else {
        // Attempt PDO DB connection & verify settings
        try {
            $dsn = "mysql:host={\$db_host};charset=utf8mb4";
            $options = [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_TIMEOUT => 5 // 5 second timeout for validation
            ];
            $test_pdo = new PDO(\$dsn, \$db_user, \$db_pass, \$options);
            
            // Create database if it does not exist
            \$test_pdo->exec("CREATE DATABASE IF NOT EXISTS \`{\$db_name}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;");
            \$test_pdo->exec("USE \`{\$db_name}\`;");

            // Define tables creation queries
            \$tablesSql = [
                "users" => "
                    CREATE TABLE IF NOT EXISTS users (
                        id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                        user_id BIGINT NOT NULL UNIQUE,
                        username VARCHAR(255) NULL,
                        first_name VARCHAR(255) NULL,
                        step TINYINT NOT NULL DEFAULT 1,
                        action_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        is_blocked TINYINT(1) DEFAULT 0,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
                ",
                "callback_logs" => "
                    CREATE TABLE IF NOT EXISTS callback_logs (
                        id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        callback_data VARCHAR(255),
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
                ",
                "worker_logs" => "
                    CREATE TABLE IF NOT EXISTS worker_logs (
                        id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        action_type VARCHAR(100),
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
                "
            ];

            // Execute schema provisioning
            foreach (\$tablesSql as \$tableName => \$sql) {
                \$test_pdo->exec(\$sql);
            }

            // Create optimization and lock indexes on users table
            \$indexes = [
                "CREATE UNIQUE INDEX IF NOT EXISTS idx_user_id ON users(user_id);",
                "CREATE INDEX IF NOT EXISTS idx_step ON users(step);",
                "CREATE INDEX IF NOT EXISTS idx_action_timestamp ON users(action_timestamp);",
                "CREATE INDEX IF NOT EXISTS idx_step_timestamp ON users(step, action_timestamp);"
            ];

            foreach (\$indexes as \$indexSql) {
                try {
                    \$test_pdo->exec(\$indexSql);
                } catch (PDOException \$idxEx) {
                    // Index may already exist (compatibility handling under MySQL versions)
                }
            }

            // Generate config.php dynamic values
            \$configContent = "<?php" . PHP_EOL;
            \$configContent .= "/**" . PHP_EOL;
            \$configContent .= " * Dynamic Telegram Bot Configuration File." . PHP_EOL;
            \$configContent .= " * Auto-generated by install.php" . PHP_EOL;
            \$configContent .= " */" . PHP_EOL . PHP_EOL;
            \$configContent .= "declare(strict_types=1);" . PHP_EOL . PHP_EOL;
            \$configContent .= "define('DB_HOST', " . var_export(\$db_host, true) . ");" . PHP_EOL;
            \$configContent .= "define('DB_NAME', " . var_export(\$db_name, true) . ");" . PHP_EOL;
            \$configContent .= "define('DB_USER', " . var_export(\$db_user, true) . ");" . PHP_EOL;
            \$configContent .= "define('DB_PASS', " . var_export(\$db_pass, true) . ");" . PHP_EOL;
            \$configContent .= "define('TELEGRAM_BOT_TOKEN', " . var_export(\$bot_token, true) . ");" . PHP_EOL;
            \$configContent .= "define('CHANNEL_ID', " . var_export(\$channel_id, true) . ");" . PHP_EOL;

            if (file_put_contents(__DIR__ . '/config.php', \$configContent) === false) {
                throw new Exception("Unable to write config.php. Please ensure directory write permissions.");
            }

            \$success = true;
        } catch (PDOException \$e) {
            \$error = "Database Error: " . \$e->getMessage();
        } catch (Exception \$e) {
            \$error = "Installation Error: " . \$e->getMessage();
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Telegram Funnel Bot Installer</title>
    <!-- Modern Bootstrap Styles -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Inter', sans-serif;
            background-color: #f3f4f6;
            color: #1f2937;
        }
        .card {
            border: none;
            border-radius: 12px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
        }
    </style>
</head>
<body class="py-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 col-lg-6">
                
                <div class="text-center mb-4">
                    <h2 class="fw-bold text-primary">Telegram Funnel Bot</h2>
                    <p class="text-muted">Enterprise-Grade Setup Wizard</p>
                </div>

                <?php if (\$success): ?>
                    <div class="card bg-white p-4">
                        <div class="card-body text-center">
                            <div class="mb-3">
                                <span class="badge bg-success py-2 px-3 fs-5">✓ Success</span>
                            </div>
                            <h3 class="fw-bold mb-3">Installation Completed!</h3>
                            <p class="text-secondary align-left text-start">
                                The schema has been successfully created and your parameters have been persisted to <code>config.php</code>.
                            </p>
                            
                            <hr>

                            <h5 class="fw-bold text-start text-dark mb-2">Next Steps:</h5>
                            <ol class="text-start fs-7 text-secondary">
                                <li class="mb-2"><strong>Set Up Telegram Webhook</strong>: Run this HTTP trigger in your browser (replace URL with your domain):<br>
                                    <code class="d-block bg-light p-2 mt-1 border-radius text-break" style="font-size: 11px;">https://api.telegram.org/bot<?php echo htmlspecialchars(\$bot_token); ?>/setWebhook?url=https://yourdomain.com/webhook_handler.php&allowed_updates=["message","callback_query","chat_member"]</code>
                                </li>
                                <li class="mb-2"><strong>Start Watchdog Cron</strong>: Launch the worker daemon inside your server Terminal:<br>
                                    <code class="d-block bg-light p-2 mt-1 border-radius text-break" style="font-size: 11px;">chmod +x cron_job.sh && ./cron_job.sh</code>
                                </li>
                                <li class="mb-2"><strong>Channel Check</strong>: Ensure your Telegram Bot is added as an <strong>Administrator</strong> inside your Telegram channel.</li>
                            </ol>

                            <div class="mt-4">
                                <a href="install.php" class="btn btn-outline-primary btn-sm">Configure Again</a>
                            </div>
                        </div>
                    </div>
                <?php else: ?>
                    <div class="card bg-white p-4">
                        <div class="card-body">
                            <form method="POST">
                                <input type="hidden" name="action" value="setup">

                                <?php if (\$error): ?>
                                    <div class="alert alert-danger" role="alert">
                                        <?php echo htmlspecialchars(\$error); ?>
                                    </div>
                                <?php endif; ?>

                                <h5 class="fw-bold mb-3 text-secondary border-bottom pb-2">MySQL Database Details</h5>
                                
                                <div class="mb-3">
                                    <label class="form-label font-medium mb-1">Database Host</label>
                                    <input type="text" class="form-control" name="db_host" value="localhost" placeholder="e.g. localhost, 127.0.0.1" required>
                                </div>

                                <div class="mb-3">
                                    <label class="form-label font-medium mb-1">Database Name</label>
                                    <input type="text" class="form-control" name="db_name" placeholder="e.g. telegram_funnel_db" required>
                                </div>

                                <div class="row">
                                    <div class="col-sm-6 mb-3">
                                        <label class="form-label font-medium mb-1">Database User</label>
                                        <input type="text" class="form-control" name="db_user" placeholder="root" required>
                                    </div>
                                    <div class="col-sm-6 mb-3">
                                        <label class="form-label font-medium mb-1">Database Password</label>
                                        <input type="password" class="form-control" name="db_pass" placeholder="Leave empty if none">
                                    </div>
                                </div>

                                <h5 class="fw-bold mt-4 mb-3 text-secondary border-bottom pb-2">Telegram Integration Keys</h5>

                                <div class="mb-3">
                                    <label class="form-label font-medium mb-1">Telegram Bot Token</label>
                                    <input type="text" class="form-control text-monospace" style="font-size: 13px;" name="bot_token" placeholder="123456789:ABCdefGhIJKlmNoPQRsTUVwxyZ" required>
                                    <div class="form-text">Generate via @BotFather in Telegram.</div>
                                </div>

                                <div class="mb-3">
                                    <label class="form-label font-medium mb-1">Channel ID (Optional)</label>
                                    <input type="text" class="form-control" name="channel_id" placeholder="e.g. -100123456789">
                                    <div class="form-text">Telegram channel numeric identifier (with -100 prefix).</div>
                                </div>

                                <div class="mt-4 pt-2">
                                    <button type="submit" class="btn btn-primary w-full w-100 py-2 fw-semibold">Install & Initialize Database</button>
                                </div>
                            </form>
                        </div>
                    </div>
                <?php endif; ?>

            </div>
        </div>
    </div>
</body>
</html>`
  },
  'db_connect.php': {
    desc: 'Secure database abstraction layer using prepared state PDO handlers with safe exception catchers.',
    lang: 'php',
    val: `<?php
/**
 * db_connect.php
 * 
 * Secure DB Connection layer using PDO.
 * Part of the Enterprise Telegram Funnel Bot System.
 */

declare(strict_types=1);

// We require the config file which contains database credentials
$config_path = __DIR__ . '/config.php';

if (!file_exists($config_path)) {
    if (basename($_SERVER['PHP_SELF']) !== 'install.php') {
        http_response_code(500);
        echo json_encode([
            'ok' => false,
            'error' => 'System is not configured. Please run install.php first.'
        ]);
        exit;
    }
} else {
    require_once $config_path;
}

try {
    // Construct PDO with proper UTF-8 charset
    $dsn = sprintf(
        "mysql:host=%s;dbname=%s;charset=utf8mb4",
        DB_HOST,
        DB_NAME
    );

    $options = [
        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES   => false, // True prepared statements for security
    ];

    $pdo = new PDO($dsn, DB_USER, DB_PASS, $options);
} catch (PDOException $e) {
    error_log("Database Connection Failed: " . $e->getMessage());
    
    if (basename($_SERVER['PHP_SELF']) !== 'install.php') {
        http_response_code(500);
        echo json_encode([
            'ok' => false,
            'error' => 'Database connection failed. Please check error.log.'
        ]);
        exit;
    }
}`
  },
  'telegram_api.php': {
    desc: 'cURL based HTTP client for Telegram Bot API supporting complex methods, error parsing, and automated 3-tier exponential backoff retry controls.',
    lang: 'php',
    val: `<?php
/**
 * telegram_api.php
 * 
 * Production-ready cURL based Telegram API Library.
 * Handles retry logic, error parsing, and logging.
 */

declare(strict_types=1);

require_once __DIR__ . '/db_connect.php';

class TelegramAPI {
    private string $botToken;
    private string $apiUrl;
    private ?PDO $pdo;

    public function __construct(string $botToken, ?PDO $pdo = null) {
        $this->botToken = $botToken;
        $this->apiUrl = "https://api.telegram.org/bot" . $this->botToken . "/";
        $this->pdo = $pdo;
    }

    /**
     * Executes a cURL request to the Telegram API with exponential backoff on transient failures.
     */
    private function makeRequest(string $method, array $params = []): array {
        $url = $this->apiUrl . $method;
        $maxAttempts = 3;
        $attempt = 0;
        $backoff = 1;

        while ($attempt < $maxAttempts) {
            $attempt++;
            $ch = curl_init();
            
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_POST, true);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_TIMEOUT, 10);
            curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($params));
            curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);

            $response = curl_exec($ch);
            $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            $curlError = curl_error($ch);
            curl_close($ch);

            if ($response === false) {
                $this->logError("cURL Error on '{\$method}' (Attempt {\$attempt}): {\$curlError}");
                if ($attempt < $maxAttempts) {
                    sleep($backoff);
                    $backoff *= 2;
                    continue;
                }
                throw new Exception("Telegram API cURL Failure: " . $curlError);
            }

            $result = json_decode($response, true);
            if (json_last_error() !== JSON_ERROR_NONE) {
                $this->logError("JSON Decode Error on '{\$method}' Response (HTTP {\$httpCode}): " . json_last_error_msg());
                throw new Exception("Invalid JSON received from Telegram API");
            }

            if ($result['ok'] === true) {
                return $result;
            }

            $errorCode = $result['error_code'] ?? 0;
            $description = $result['description'] ?? 'Unknown Telegram error';

            $this->logError("Telegram API Error on '{\$method}': [Code {\$errorCode}] {\$description}");

            if ($errorCode === 403 || strpos(strtolower($description), 'blocked') !== false) {
                if (isset($params['chat_id']) && $this->pdo) {
                    $this->markUserBlocked((int)$params['chat_id']);
                }
            }

            if ($errorCode >= 400 && $errorCode < 500) {
                return $result;
            }

            if ($attempt < $maxAttempts) {
                sleep($backoff);
                $backoff *= 2;
                continue;
            }

            return $result;
        }

        throw new Exception("Telegram API query failed after {\$maxAttempts} attempts.");
    }

    public function sendMessage(int $chatId, string $text, array $replyMarkup = []): array {
        $params = [
            'chat_id' => $chatId,
            'text' => $text,
            'parse_mode' => 'HTML',
            'disable_web_page_preview' => true
        ];
        if (!empty($replyMarkup)) {
            $params['reply_markup'] = $replyMarkup;
        }
        return $this->makeRequest('sendMessage', $params);
    }

    public function sendPhoto(int $chatId, string $photoUrl, string $caption = '', array $replyMarkup = []): array {
        $params = [
            'chat_id' => $chatId,
            'photo' => $photoUrl,
            'caption' => $caption,
            'parse_mode' => 'HTML'
        ];
        if (!empty($replyMarkup)) {
            $params['reply_markup'] = $replyMarkup;
        }
        return $this->makeRequest('sendPhoto', $params);
    }

    public function sendMediaGroup(int $chatId, array $photoUrls, string $captionForFirst = ''): array {
        $media = [];
        foreach ($photoUrls as $index => $url) {
            $item = [
                'type' => 'photo',
                'media' => $url,
            ];
            if ($index === 0 && !empty($captionForFirst)) {
                $item['caption'] = $captionForFirst;
                $item['parse_mode'] = 'HTML';
            }
            $media[] = $item;
        }

        $params = [
            'chat_id' => $chatId,
            'media' => $media
        ];
        return $this->makeRequest('sendMediaGroup', $params);
    }

    public function answerCallbackQuery(string $callbackQueryId, string $text = '', bool $showAlert = false): array {
        $params = [
            'callback_query_id' => $callbackQueryId
        ];
        if (!empty($text)) {
            $params['text'] = $text;
            $params['show_alert'] = $showAlert;
        }
        return $this->makeRequest('answerCallbackQuery', $params);
    }

    private function markUserBlocked(int $userId): void {
        try {
            $stmt = $this->pdo->prepare("UPDATE users SET is_blocked = 1, updated_at = CURRENT_TIMESTAMP WHERE user_id = ?");
            $stmt->execute([$userId]);
            $this->logError("User {\$userId} has blocked the bot. Marked as is_blocked = 1 in database.");
        } catch (PDOException $e) {
            $this->logError("Failed to update user {\$userId} blocked state: " . $e->getMessage());
        }
    }

    private function logError(string $message): void {
        $logDir = __DIR__ . '/logs';
        if (!is_dir($logDir)) {
            mkdir($logDir, 0755, true);
        }
        $logFile = $logDir . '/error.log';
        $timestamp = date('Y-m-d H:i:s');
        file_put_contents($logFile, "[{\$timestamp}] {\$message}" . PHP_EOL, FILE_APPEND);
    }
}`
  },
  'webhook_handler.php': {
    desc: 'Handles incoming traffic for Joins (`chat_member`), Button Clicks (`callback_query`), and Command Starts (`/START`). Implements row-level transactions to shield key resources from duplication.',
    lang: 'php',
    val: `<?php
/**
 * webhook_handler.php
 * 
 * Telegram Webhook Handler.
 * Automatically processes chat member joins, callbacks, and slash commands.
 */

declare(strict_types=1);

header('Content-Type: application/json');

require_once __DIR__ . '/db_connect.php';
require_once __DIR__ . '/telegram_api.php';

function writeWebhookLog(string $message): void {
    $logDir = __DIR__ . '/logs';
    if (!is_dir($logDir)) {
        mkdir($logDir, 0755, true);
    }
    $logFile = $logDir . '/webhook.log';
    $timestamp = date('Y-m-d H:i:s');
    file_put_contents($logFile, "[{\$timestamp}] {\$message}" . PHP_EOL, FILE_APPEND);
}

$rawInput = file_get_contents('php://input');
if (empty($rawInput)) {
    writeWebhookLog("Warning: Received empty payload.");
    echo json_encode(['ok' => false, 'error' => 'No payload']);
    exit;
}

$update = json_decode($rawInput, true);
if (json_last_error() !== JSON_ERROR_NONE) {
    writeWebhookLog("Error: Invalid JSON Payload received: " . json_last_error_msg());
    echo json_encode(['ok' => false, 'error' => 'Invalid JSON']);
    exit;
}

writeWebhookLog("Received update: " . json_encode($update));

if (!defined('TELEGRAM_BOT_TOKEN')) {
    writeWebhookLog("Error: Bot token is undefined in configuration. Run install.php.");
    echo json_encode(['ok' => false, 'error' => 'System unconfigured']);
    exit;
}

$telegram = new TelegramAPI(TELEGRAM_BOT_TOKEN, $pdo);

try {
    // 1. JOIN EVENT (chat_member status update)
    if (isset($update['chat_member'])) {
        $chatMemberUpdate = $update['chat_member'];
        $chatId = (int)$chatMemberUpdate['chat']['id'];
        $newMember = $chatMemberUpdate['new_chat_member'];
        $user = $newMember['user'];
        $status = $newMember['status'];

        $userId = (int)$user['id'];
        $username = $user['username'] ?? null;
        $firstName = $user['first_name'] ?? 'User';

        if ($status === 'member') {
            $checkStmt = $pdo->prepare("SELECT user_id, step FROM users WHERE user_id = ?");
            $checkStmt->execute([$userId]);
            $existingUser = $checkStmt->fetch();

            if (!$existingUser) {
                $pdo->beginTransaction();
                try {
                    $insertStmt = $pdo->prepare("
                        INSERT INTO users (user_id, username, first_name, step, action_timestamp, is_blocked)
                        VALUES (?, ?, ?, 1, CURRENT_TIMESTAMP, 0)
                        ON DUPLICATE KEY UPDATE 
                            username = VALUES(username),
                            first_name = VALUES(firstName)
                    ");
                    $insertStmt->execute([$userId, $username, $firstName]);
                    $pdo->commit();
                } catch (Exception $dbEx) {
                    $pdo->rollBack();
                    throw $dbEx;
                }

                $welcomeText = "🎁 <b>Welcome!</b>\\n\\nClaim your bonus below. 👇";
                $keyboard = [
                    'inline_keyboard' => [[
                        ['text' => '🎁 GET BONUS', 'callback_data' => 'get_bonus']
                    ]]
                ];

                $telegram->sendMessage($userId, $welcomeText, $keyboard);
            }
        }
        
        echo json_encode(['ok' => true]);
        exit;
    }

    // 2. CALLBACK QUERY (GET BONUS CLICK)
    if (isset($update['callback_query'])) {
        $callbackQuery = $update['callback_query'];
        $callbackQueryId = $callbackQuery['id'];
        $callbackData = $callbackQuery['data'] ?? '';
        $user = $callbackQuery['from'];
        $userId = (int)$user['id'];

        if ($callbackData === 'get_bonus') {
            $pdo->beginTransaction();
            try {
                // SELECT FOR UPDATE to lock row against race conditions
                $stmt = $pdo->prepare("SELECT step FROM users WHERE user_id = ? FOR UPDATE");
                $stmt->execute([$userId]);
                $userState = $stmt->fetch();

                if (!$userState) {
                    $firstName = $user['first_name'] ?? 'User';
                    $username = $user['username'] ?? null;
                    $stmtInsert = $pdo->prepare("
                        INSERT INTO users (user_id, username, first_name, step, action_timestamp) 
                        VALUES (?, ?, ?, 1, CURRENT_TIMESTAMP)
                    ");
                    $stmtInsert->execute([$userId, $username, $firstName]);
                    $currentStep = 1;
                } else {
                    $currentStep = (int)$userState['step'];
                }

                if ($currentStep === 1) {
                    $updateStmt = $pdo->prepare("
                        UPDATE users 
                        SET step = 2, action_timestamp = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP 
                        WHERE user_id = ?
                    ");
                    $updateStmt->execute([$userId]);

                    $logStmt = $pdo->prepare("
                        INSERT INTO callback_logs (user_id, callback_data) 
                        VALUES (?, 'get_bonus')
                    ");
                    $logStmt->execute([$userId]);

                    $pdo->commit();

                    $telegram->answerCallbackQuery($callbackQueryId);

                    $photoUrl = "https://i.ibb.co/1Y39dQgM/IMG-20260604-WA0020.jpg";
                    $captionText = "If you're looking for <b>\\\"quick and easy,\\\"</b>\\nyou're not looking for me.\\n\\n👛🔄 But if you're ready for the real working system,\\nclick <b>READY</b> below⤵️";
                    
                    $keyboard = [
                        'inline_keyboard' => [[
                            ['text' => 'READY BELOW', 'url' => 'https://t.me/Anita_Desai_here']
                        ]]
                    ];

                    $telegram->sendPhoto($userId, $photoUrl, $captionText, $keyboard);
                } else {
                    $pdo->commit();
                    $telegram->answerCallbackQuery($callbackQueryId, "Bonus already claimed!");
                }
            } catch (Exception $txEx) {
                $pdo->rollBack();
                $telegram->answerCallbackQuery($callbackQueryId, "Error processing click.");
                throw $txEx;
            }
        }
        echo json_encode(['ok' => true]);
        exit;
    }

    // 3. /START SHIFT REDIRECT Command
    if (isset($update['message'])) {
        $msg = $update['message'];
        $from = $msg['from'] ?? null;
        $text = trim($msg['text'] ?? '');

        if ($from) {
            $userId = (int)$from['id'];
            $username = $from['username'] ?? null;
            $firstName = $from['first_name'] ?? 'User';

            if (strcasecmp($text, '/start') === 0) {
                $checkStmt = $pdo->prepare("SELECT user_id FROM users WHERE user_id = ?");
                $checkStmt->execute([$userId]);
                if (!$checkStmt->fetch()) {
                    $insertStmt = $pdo->prepare("
                        INSERT INTO users (user_id, username, first_name, step, action_timestamp) 
                        VALUES (?, ?, ?, 1, CURRENT_TIMESTAMP)
                    ");
                    $insertStmt->execute([$userId, $username, $firstName]);
                }

                $redirectText = "👋🏻 <b>I have a quick update for you.</b>\\n\\nPlease message me privately👉🏻\\n\\n@Anita_Desai_here";
                $telegram->sendMessage($userId, $redirectText);
            }
        }
        echo json_encode(['ok' => true]);
        exit;
    }

    echo json_encode(['ok' => true, 'info' => 'Unhandled update type']);

} catch (Exception $ex) {
    writeWebhookLog("Critical Error in Webhook Handler: " . $ex->getMessage());
    echo json_encode(['ok' => false, 'error' => $ex->getMessage()]);
}
`
  },
  'timer_worker.php': {
    desc: 'The heart of automation: tracks stagnant queues (10s and 5s respectively) using transactional FOR UPDATE row locking. Modulates and updates users through sequence flows without duplicates.',
    lang: 'php',
    val: `<?php
/**
 * timer_worker.php
 * 
 * High-performance state-machine cron worker daemon.
 */

declare(strict_types=1);

set_time_limit(0);

require_once __DIR__ . '/db_connect.php';
require_once __DIR__ . '/telegram_api.php';

if (php_sapi_name() !== 'cli') {
    die("This script must be run via the PHP Command Line Interface (CLI)." . PHP_EOL);
}

if (!defined('TELEGRAM_BOT_TOKEN')) {
    die("Error: TELEGRAM_BOT_TOKEN is not defined. Ensure config.php is set up." . PHP_EOL);
}

$telegram = new TelegramAPI(TELEGRAM_BOT_TOKEN, $pdo);

function writeWorkerLog(string $message): void {
    $logDir = __DIR__ . '/logs';
    if (!is_dir($logDir)) {
        mkdir($logDir, 0755, true);
    }
    $logFile = $logDir . '/worker.log';
    $timestamp = date('Y-m-d H:i:s');
    file_put_contents($logFile, "[{\$timestamp}] {\$message}" . PHP_EOL, FILE_APPEND);
}

while (true) {
    try {
        // --- 1. CONVERT BATCH OF STEP 1 USERS (SALARY IMAGE after 10s) ---
        $stmt = $pdo->prepare("
            SELECT user_id, first_name 
            FROM users 
            WHERE step = 1 
              AND is_blocked = 0
              AND TIMESTAMPDIFF(SECOND, action_timestamp, NOW()) >= 10
            LIMIT 100
        ");
        $stmt->execute();
        $step1Candidates = $stmt->fetchAll();

        foreach ($step1Candidates as $user) {
            $userId = (int)$user['user_id'];

            $pdo->beginTransaction();
            try {
                $lockStmt = $pdo->prepare("SELECT step FROM users WHERE user_id = ? FOR UPDATE");
                $lockStmt->execute([$userId]);
                $currentUser = $lockStmt->fetch();

                if ($currentUser && (int)$currentUser['step'] === 1) {
                    $updateStmt = $pdo->prepare("
                        UPDATE users 
                        SET step = 3, action_timestamp = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP 
                        WHERE user_id = ?
                    ");
                    $updateStmt->execute([$userId]);

                    $logStmt = $pdo->prepare("INSERT INTO worker_logs (user_id, action_type) VALUES (?, 'send_salary_message')");
                    $logStmt->execute([$userId]);

                    $pdo->commit();

                    $photoUrl = "https://i.ibb.co/4nYtsQ6z/IMG-20260604-WA0019.jpg";
                    $captionText = "💵➕💰 <b>Start building a supplemental income to your salary or pension today</b>\\n\\nIts, will you start now or in a year?";
                    
                    $telegram->sendPhoto($userId, $photoUrl, $captionText);
                } else {
                    $pdo->commit();
                }
            } catch (Exception $txEx) {
                $pdo->rollBack();
                writeWorkerLog("Error handling Step 1 database loop: " . $txEx->getMessage());
                usleep(250000);
            }
        }

        // --- 2. CONVERT BATCH OF STEP 3 USERS (MEDIA GROUP after 5s) ---
        $stmt = $pdo->prepare("
            SELECT user_id, first_name 
            FROM users 
            WHERE step = 3 
              AND is_blocked = 0
              AND TIMESTAMPDIFF(SECOND, action_timestamp, NOW()) >= 5
            LIMIT 100
        ");
        $stmt->execute();
        $step3Candidates = $stmt->fetchAll();

        foreach ($step3Candidates as $user) {
            $userId = (int)$user['user_id'];

            $pdo->beginTransaction();
            try {
                $lockStmt = $pdo->prepare("SELECT step FROM users WHERE user_id = ? FOR UPDATE");
                $lockStmt->execute([$userId]);
                $currentUser = $lockStmt->fetch();

                if ($currentUser && (int)$currentUser['step'] === 3) {
                    $updateStmt = $pdo->prepare("
                        UPDATE users 
                        SET step = 4, action_timestamp = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP 
                        WHERE user_id = ?
                    ");
                    $updateStmt->execute([$userId]);

                    $logStmt = $pdo->prepare("INSERT INTO worker_logs (user_id, action_type) VALUES (?, 'send_media_group')");
                    $logStmt->execute([$userId]);

                    $pdo->commit();

                    $mediaPhotos = [
                        "https://i.ibb.co/whR6Hdpg/IMG-20260604-WA0015.jpg",
                        "https://i.ibb.co/8QZqWVT/IMG-20260604-WA0018.jpg",
                        "https://i.ibb.co/7JrfWntY/IMG-20260604-WA0016.jpg",
                        "https://i.ibb.co/9kJ5z8sB/IMG-20260604-WA0017.jpg"
                    ];

                    $captionText = "🧿 <b>Activate Code: NEW-1 to join with a welcome bonus!</b>\\n\\nBest conditions and bonuses already available to you!\\n\\nClick /START to continue!";

                    $telegram->sendMediaGroup($userId, $mediaPhotos, $captionText);
                } else {
                    $pdo->commit();
                }
            } catch (Exception $txEx) {
                $pdo->rollBack();
                writeWorkerLog("Error handling Step 3 database loop: " . $txEx->getMessage());
                usleep(250000);
            }
        }

    } catch (Exception $globalEx) {
        writeWorkerLog("Critical Error in Worker Loop: " . $globalEx->getMessage());
        sleep(5);
    }

    sleep(2);
}
`
  },
  'cron_job.sh': {
    desc: 'Unix daemon shell task to act as a resilient watchdog wrapping the worker, restoring execution upon any crash or container reboot.',
    lang: 'bash',
    val: `#!/bin/bash
# ----------------------------------------------------
# Telegram Funnel Bot - Worker Watchdog Script
# Keeps timer_worker.php running indefinitely.
# ----------------------------------------------------

echo "Initializing Telegram Bot Watchdog Daemon..."

cd "$(dirname "$0")"

while true
do
    echo "Starting state-machine worker processor (timer_worker.php)..."
    php timer_worker.php
    
    echo "Worker process exited with code $?. Restarting in 2 seconds..."
    sleep 2
done`
  }
};
